import { existsSync, readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { NextResponse } from "next/server";
import { createServiceClient } from "@/lib/supabase/service";
import { validateCronAuth } from "@/lib/security/cron-auth";

/**
 * Cron: OKF database-schema bundle health check.
 *
 * The `docs/db/okf` bundle is a BUILD-TIME artifact generated by
 * `scripts/generate-db-okf.mjs` (run `bun run gen:db-okf` in CI / locally).
 * A serverless function cannot regenerate it — the runtime filesystem is
 * read-only and ephemeral, so writing repo files at request time is not
 * possible. This endpoint therefore does NOT regenerate anything; it reports
 * whether the committed bundle is present and how large it is, so a scheduled
 * ping can surface a missing/empty bundle (e.g. a CI step that failed to run
 * the generator). It keeps the standard cron auth gate.
 */

// docs/db/okf relative to the repo root. In the Next.js server the process cwd
// is the web app root (apps/web), so walk up to the monorepo root.
const BUNDLE_DIR = join(process.cwd(), "..", "..", "docs", "db", "okf");

export interface OkfEnrichRouteDeps {
  createServiceClient?: typeof createServiceClient;
  validateCronAuth?: typeof validateCronAuth;
  bundleDir?: string;
}

function readIndexTimestamp(indexPath: string): string | null {
  try {
    const content = readFileSync(indexPath, "utf8");
    const match = content.match(/^timestamp:\s*(.+)$/m);
    return match ? match[1].trim() : null;
  } catch {
    return null;
  }
}

export function createOkfEnrichGetHandler(deps: OkfEnrichRouteDeps = {}) {
  const validateCronAuthFn = deps.validateCronAuth ?? validateCronAuth;
  // Service client is intentionally unused for this pure-docs health check, but
  // we keep the binding so future DB-backed staleness checks have a wired path
  // and the auth posture matches the other cron routes.
  const createServiceClientFn = deps.createServiceClient ?? createServiceClient;
  void createServiceClientFn;
  const bundleDir = deps.bundleDir ?? BUNDLE_DIR;

  return async function GET(request: Request) {
    const authError = validateCronAuthFn(request);
    if (authError) return authError;

    try {
      if (!existsSync(bundleDir)) {
        return NextResponse.json({
          ok: false,
          bundle_present: false,
          reason: "bundle_dir_missing",
          hint: "Run `bun run gen:db-okf` in CI to generate docs/db/okf.",
        });
      }

      const files = readdirSync(bundleDir).filter((f) => f.endsWith(".md"));
      const tableDocCount = files.filter((f) => f !== "index.md").length;
      const hasIndex = files.includes("index.md");
      const indexTimestamp = hasIndex ? readIndexTimestamp(join(bundleDir, "index.md")) : null;

      const healthy = hasIndex && tableDocCount > 0;

      return NextResponse.json({
        ok: healthy,
        bundle_present: true,
        has_index: hasIndex,
        table_doc_count: tableDocCount,
        index_timestamp: indexTimestamp,
        ...(healthy ? {} : { reason: "bundle_incomplete" }),
      });
    } catch (error) {
      console.error("[okf-enrich] Error:", error);
      return NextResponse.json({ error: "Failed to inspect OKF bundle" }, { status: 500 });
    }
  };
}
