import { NextResponse } from "next/server";
import { z } from "zod";
import { createClient } from "@/lib/supabase/server";
import { createServiceClient } from "@/lib/supabase/service";
import { checkRateLimit, buildRateLimitResponse } from "@/lib/security/rate-limit";
import { validateJson, ValidationError, baseSchemas } from "@/lib/security/validation";
import { getOrgMemberRole } from "@/lib/parents/auth";

const createInviteSchema = z.object({
  expires_at: z
    .string()
    .datetime()
    .optional()
    .nullable()
    .refine(
      (v) => v == null || new Date(v) > new Date(),
      { message: "expires_at must be a future date" }
    ),
});

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

interface RouteParams {
  params: Promise<{ organizationId: string }>;
}

export async function POST(req: Request, { params }: RouteParams) {
  const { organizationId } = await params;

  const orgIdParsed = baseSchemas.uuid.safeParse(organizationId);
  if (!orgIdParsed.success) {
    return NextResponse.json({ error: "Invalid organization id" }, { status: 400 });
  }

  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  const rateLimit = checkRateLimit(req, {
    userId: user?.id ?? null,
    feature: "org parents invite",
    limitPerIp: 20,
    limitPerUser: 10,
  });

  if (!rateLimit.ok) {
    return buildRateLimitResponse(rateLimit);
  }

  const respond = (payload: unknown, status = 200) =>
    NextResponse.json(payload, { status, headers: rateLimit.headers });

  if (!user) {
    return respond({ error: "Unauthorized" }, 401);
  }

  // Admin only
  const role = await getOrgMemberRole(supabase, user.id, organizationId);
  if (role !== "admin") {
    return respond({ error: "Forbidden" }, 403);
  }

  let body;
  try {
    body = await validateJson(req, createInviteSchema, { maxBodyBytes: 4_000 });
  } catch (error) {
    if (error instanceof ValidationError) {
      return respond({ error: error.message, details: error.details }, 400);
    }
    return respond({ error: "Invalid request" }, 400);
  }

  const serviceSupabase = createServiceClient();

  // Deduplication: return the existing non-expired pending invite if one exists.
  // This prevents invite-list clutter when an admin clicks "Create Invite" multiple times.
  // A new invite is only created when none is pending (or all have expired/been revoked).
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { data: existingInvite } = await (serviceSupabase as any)
    .from("parent_invites")
    .select("id,code,expires_at,status,created_at")
    .eq("organization_id", organizationId)
    .eq("status", "pending")
    .gt("expires_at", new Date().toISOString())
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle();

  if (existingInvite) {
    return respond({ invite: existingInvite });
  }

  // Create new invite (code generated by DB default; no email required)
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { data: invite, error: insertError } = await (serviceSupabase as any)
    .from("parent_invites")
    .insert({
      organization_id: organizationId,
      invited_by: user.id,
      ...(body.expires_at != null ? { expires_at: body.expires_at } : {}),
    })
    .select("id,code,expires_at,status,created_at")
    .single();

  if (insertError || !invite) {
    console.error("[org/parents/invite POST] DB error:", insertError);
    return respond({ error: "Failed to create invite" }, 500);
  }

  return respond({ invite });
}
