import { NextResponse } from "next/server";
import { z } from "zod";
import { createClient } from "@/lib/supabase/server";
import { createServiceClient } from "@/lib/supabase/service";
import { checkRateLimit, buildRateLimitResponse } from "@/lib/security/rate-limit";
import { validateJson, ValidationError, baseSchemas } from "@/lib/security/validation";
import { sendEmail } from "@/lib/notifications";
import { getOrgMemberRole } from "@/lib/parents/auth";

const createInviteSchema = z.object({
  email: z.string().trim().email().max(320).transform(v => v.toLowerCase()),
});

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

interface RouteParams {
  params: Promise<{ organizationId: string }>;
}

export async function POST(req: Request, { params }: RouteParams) {
  const { organizationId } = await params;

  const orgIdParsed = baseSchemas.uuid.safeParse(organizationId);
  if (!orgIdParsed.success) {
    return NextResponse.json({ error: "Invalid organization id" }, { status: 400 });
  }

  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  const rateLimit = checkRateLimit(req, {
    userId: user?.id ?? null,
    feature: "org parents invite",
    limitPerIp: 20,
    limitPerUser: 10,
  });

  if (!rateLimit.ok) {
    return buildRateLimitResponse(rateLimit);
  }

  const respond = (payload: unknown, status = 200) =>
    NextResponse.json(payload, { status, headers: rateLimit.headers });

  if (!user) {
    return respond({ error: "Unauthorized" }, 401);
  }

  // Admin only
  const role = await getOrgMemberRole(supabase, user.id, organizationId);
  if (role !== "admin") {
    return respond({ error: "Forbidden" }, 403);
  }

  let body;
  try {
    body = await validateJson(req, createInviteSchema, { maxBodyBytes: 4_000 });
  } catch (error) {
    if (error instanceof ValidationError) {
      return respond({ error: error.message, details: error.details }, 400);
    }
    return respond({ error: "Invalid request" }, 400);
  }

  const { email } = body;
  const serviceSupabase = createServiceClient();

  // Fetch org slug for invite link and name for email
  const { data: org, error: orgError } = await serviceSupabase
    .from("organizations")
    .select("slug, name")
    .eq("id", organizationId)
    .single();

  if (orgError || !org) {
    return respond({ error: "Organization not found" }, 404);
  }

  const now = new Date().toISOString();

  // Check for existing VALID (non-expired) pending invite (idempotent — return if found)
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { data: existingInvite } = await (serviceSupabase as any)
    .from("parent_invites")
    .select("id,email,code,expires_at,status,created_at")
    .eq("organization_id", organizationId)
    .eq("email", email)
    .eq("status", "pending")
    .gt("expires_at", now)
    .maybeSingle();

  if (existingInvite) {
    return respond({ invite: existingInvite });
  }

  // Revoke any expired pending invites for this org+email before inserting a fresh one.
  // Prevents unique-constraint violations if the DB has an active-pending uniqueness rule.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  await (serviceSupabase as any)
    .from("parent_invites")
    .update({ status: "revoked" })
    .eq("organization_id", organizationId)
    .eq("email", email)
    .eq("status", "pending")
    .lte("expires_at", now);

  // Create new invite (code generated by DB default)
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { data: invite, error: insertError } = await (serviceSupabase as any)
    .from("parent_invites")
    .insert({
      organization_id: organizationId,
      email,
      invited_by: user.id,
    })
    .select("id,email,code,expires_at,status,created_at")
    .single();

  if (insertError || !invite) {
    console.error("[org/parents/invite POST] DB error:", insertError);
    return respond({ error: "Failed to create invite" }, 500);
  }

  // Send invite email (non-blocking — log failure but don't fail request)
  const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? new URL(req.url).origin;
  const inviteLink = `${appUrl}/app/parents-join?org=${organizationId}&code=${invite.code}`;
  const emailResult = await sendEmail({
    to: email,
    subject: `You've been invited to join ${org.name} as a parent/guardian`,
    body: `Hello,\n\nYou've been invited to join ${org.name} on TeamMeet.\n\nAccept your invitation here:\n${inviteLink}\n\nThis invitation expires in 7 days.\n\nIf you did not expect this invitation, you can safely ignore this email.`,
  });

  if (!emailResult.success) {
    console.error("[org/parents/invite POST] Email send failed:", emailResult.error);
  }

  return respond({ invite });
}
